### ISSUE TITLE
用cner数据集跑的时候，data_loader报KeyError

### ISSUE THREAD

**Issue by JeremySun1224** [taishan1994/pytorch_TPLinker_Plus_Ner#2]
```
Traceback (most recent call last):
  File "main.py", line 251, in <module>
    bertForNer.train()
  File "main.py", line 42, in train
    for step, batch_data in enumerate(self.train_loader):
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/root/sx/sx_pytorch/pytorch_TPLinker_Plus_Ner/data_loader.py", line 75, in collate_fn
    batch_labels[i, self.map_ij2k[s_i[0], s_i[1]], self.tag2id[s_i[2]]] = 1
KeyError: (147, 150)
```

**Comment by taishan1994** [comment]
加个异常判断，对于不正确的样本跳过就好。
